### ISSUE TITLE
개발환경 셋업

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/char-trainer#2]
## Todo
- [ ] 프로젝트 생성
- [ ] data, domain, presentation 모듈 생성
- [ ] data -> domain <- presentation 의존관계 설정
- [ ] Hilt 추가
- [ ] Ktlint 추가
- [ ] 각 모듈별 필수 라이브러리 의존성 추가

## Things to watch out for
- 레이어별 모듈로 시작하려는 이유는 일단 의존성 강제해서 고수준인 domain 부터 보호하려고
  - 가장 테스트 하기 쉬운우니 도메인 레이어 코드 테스트를 가장 먼저 해보고 싶어서. 
- 앱 기능이 커진다고 했을 때 feature 단위로 나눠보기

**Comment by omjoonkim** [comment]
숫자 단위는 시간인가요 하루인가요?

**Comment by nosorae** [comment]
시간입니다, 뒤에 h를 붙여보겠습니다!
