### ISSUE TITLE
유저(익명) 정보 확인/수정 기능

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/char-trainer#3]
## What users can do with this feature
 - 유저는 유저 정보 화면에서 아래 정보들을 확인할 수 있다.
   - (임시로 정해진) 닉네임 
   - 총 자산 금액
   - 평균 수익률
   - 전적
   - 승률
   - 차트 봉의 단위
   - 수수료
- 유저는 유저 정보 화면에서 아래 정보들을 수정할 수 있다.
  - 차트의 봉 단위 설정
  - 수수료 설정

## Todo
- [ ] User Entity 추가
- [ ] GetUserInfoUserCase 추가
  - User 엔티티를 데이터 업데이트에 반응 가능한 형태로 반환
- [ ] 유저 정보 화면 UI/UX 개발
- [ ] 유저 정보 화면을 첫 화면으로 설정한다. 

## Reference materials
- 알파스퀘어 차트게임 탭 UIUX
- 토스 UIUX

## TBD
- 닉네임과 프로필 사진은 로그인 기능과 함께 추가
