### ISSUE TITLE
차트게임 기능 - data

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/char-trainer#5]
## What users can do with this feature
 - 유저는 차트게임을 할 수 있다.
   - 캔들 형태로 차트를 볼 수 있다.
     - 캔들 차트 오른쪽에 해당하는 가격 숫자를 볼 수 있다.
   - 바 형태로 거래량을 볼 수 있다.
     - 거래량 차트 오른쪽에 해당하는 거래량 숫자를 볼 수 있다.
   - 차트를 새로고침하여 다른 최대 3번 새로운 차트로 바꿀 수 있다.
   - 게임을 시작할 수 있다.
   - 턴마다 (여러번) 매수할 수 있다.
   - 턴마다 (여러번) 매도할 수 있다.
   - 다음 턴(봉)을 불러올 수 있다.
   - 전체 턴 중에 현재 턴은 몇턴인지 볼 수 있다.
   - 게임 진행 중간에 매수/매도 기록을 볼 수 있다.
- 유저는 차트게임 중간에 앱 또는 게임을 종료했다가 재개할 수 있다.

## Todo
- [ ] DataSource 구현
  - [ ] Network 로부터 새로운 차트 정보 Get (중복검사는 UseCase 에서)
  - [ ] DB 로부터 게임 히스토리 Create, Read
  - [ ] DB 로부터 트레이드 히스토리 Create, Read
- [ ] Repository interface 구현
