### ISSUE TITLE
게임 트레이드 내역 확인 기능

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/char-trainer#7]
## What users can do with this feature
- 유저는 종료된 게임에 한해서 해당 게임 전/후 자산을 비교하고 수익을 확인할 수 있다. 
- 유저는 하나의 게임에서 일어난 트레이드 내역을 (게임 종료 여부과 관계없이) 확인할 수 있다.
- 유저는 트레이드 내역으로 해당 트레이드가 발생한 턴/매수가격/매도가격/수수료 및 세금/체결금액/실현손익을 확인할 수 있다.
- 유저는 종료되지 않은 게임을 재개할 수 있다.

## Todo
- [ ] Entity 작성 (이미 되어있을 수도 있음)
  - GameHistory
  - TradeHistory
- [ ] SubscribeTradeHistoryUseCase 작성 및 필요한 Repository ineterface 작성
- [ ] UI 컴포넌트 제작 및 배치
  - TopAppBar
    - 뒤로가기 아이콘 버튼
    - 타이틀 "매매 내역" 텍스트
  - 자산 변화 레이아웃 (게임 종료시에만 나옴)
    - 초기 자산 텍스트
    - 화살표 아이콘 텍스트
    - 총 평가 자산 텍스트
    - 수익 텍스트
  - 리스트
    - 해당턴/총턴 구분 텍스트
    - 매매내역 리스트 아이템 (턴/매수가격/매도가격/수수료 및 세금/체결금액/실현손익 정보 텍스트)

## Reference materials
- 알파스퀘어 차트게임
