### ISSUE TITLE
게임 내역 확인 기능

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/char-trainer#8]
## What users can do with this feature
 - 유저는 이때까지 진행한 게임을 리스트 형태로 확인할 수 있다.
 - 각 게임마다 종료여부/기업 아이콘/이름/수익률/수익을 확인할 수 있다.
 - 게임 정보에 대해 더 자세하게 확인하기 위해 "게임 트레이드 내역 화면"으로 이동할 수 있다.

## Todo
- [ ] Entity 작성
- [ ] SubscribeGameHistoryUseCase 작성 및 필요한 Repository interface 작성
- [ ] Repository interface 구현 및 구현하기 위한 DataSource 구현
- [ ] ViewModel 구현
- [ ] UI 컴포넌트 제작/배치 및 ViewModel과 연결
  - TopAppBar
    - 타이틀
  - 리스트
    - 게임 내역 리스트 아이템 (기업 아이콘 이미지, 기업 이름, 수익률/수익, 더보기 아이콘)

## Reference materials
- 알파스퀘어 차트게임
