### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by nosorae** [f-lab-edu/char-trainer#9]
## Todo
- [ ] 앱 간단 소개
- [ ] 아키텍처 시각화하여 첨부
- [ ] 화면 네비게이션 시각화하여 첨부
- [ ] gif로 스크린 샷 첨부
- [ ] 문제/어려웠던 점과 해결과정 간략히 + (길어진 경우 블로그 포스팅 후 첨부)
- [ ] 유명 레포지토리 레퍼런스 5 개 참고하고 필요할지 판단하여 추가
